'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
    },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'API Documentation',
      link: {
        type: 'generated-index',
        title: 'API Documentation',
        description: 'REST API documentation',
      },
      items: [
        'api/tasks',
        'api/get-all-tasks',
        'api/get-task-by-id',
        'api/create-task',
        'api/update-task',
        'api/delete-task',
      ],
    },
  ],
};
exports.default = sidebars;
